### ISSUE TITLE
GameDefinitionController throws EntityDoesNotExistException for non-existent game definition

### ISSUE THREAD

**Issue by HolisticDeveloper** [NemeStats/NemeStats#777]
When a game definition details URL points to a non-existent game definition, the page throws an EntityDoesNotExistException rather than returning a 404.

Example: https://nemestats.com/GameDefinition/Details/31179

View details in Rollbar: [https://rollbar.com/jakejgordon/NemeStats/items/3465/](https://rollbar.com/jakejgordon/NemeStats/items/3465/)

```
Traceback (most recent call last):
  File "C:\repos\NemeStats\Source\BusinessLogic\Logic\GameDefinitions\GameDefinitionRetriever.cs", line 209, in GetGameDefinitionDetails(System.Int32 id, System.Int32 numberOfPlayedGamesToRetrieve)
  File "C:\repos\NemeStats\Source\UI\Controllers\GameDefinitionController.cs", line 89, in Details(System.Nullable`1[System.Int32] id, BusinessLogic.Models.User.ApplicationUser currentUser)
  File "(unknown)", line 150, in lambda_method(System.Runtime.CompilerServices.Closure , System.Web.Mvc.ControllerBase , System.Object[] )
  File "System.Web.Mvc.ActionMethodDispatcher", line unknown, in Execute(System.Web.Mvc.ControllerBase controller, System.Object[] parameters)
  File "System.Web.Mvc.ReflectedActionDescriptor", line 81, in Execute(System.Web.Mvc.ControllerContext controllerContext, System.Collections.Generic.IDictionary`2[System.String,System.Object] parameters)
  File "System.Web.Mvc.ControllerActionInvoker", line unknown, in InvokeActionMethod(System.Web.Mvc.ControllerContext controllerContext, System.Web.Mvc.ActionDescriptor actionDescriptor, System.Collections.Generic.IDictionary`2[System.String,System.Object] parameters)
  File "System.Web.Mvc.Async.AsyncControllerActionInvoker", line unknown, in <BeginInvokeSynchronousActionMethod>b__39(System.IAsyncResult asyncResult, System.Web.Mvc.Async.AsyncControllerActionInvoker+ActionInvocation innerInvokeState)
  File "System.Web.Mvc.Async.AsyncResultWrapper+WrappedAsyncResult`2", line unknown, in CallEndDelegate(System.IAsyncResult asyncResult)
  File "System.Web.Mvc.Async.AsyncResultWrapper+WrappedAsyncResultBase`1", line 41, in End
  File "System.Web.Mvc.Async.AsyncControllerActionInvoker", line unknown, in EndInvokeActionMethod(System.IAsyncResult asyncResult)
  File "System.Web.Mvc.Async.AsyncControllerActionInvoker+AsyncInvocationWithFilters", line 20, in <InvokeActionMethodFilterAsynchronouslyRecursive>b__3d
  File "System.Web.Mvc.Async.AsyncControllerActionInvoker+AsyncInvocationWithFilters+<>c__DisplayClass46", line 134, in <InvokeActionMethodFilterAsynchronouslyRecursive>b__3f
  File "System.Web.Mvc.Async.AsyncControllerActionInvoker+AsyncInvocationWithFilters+<>c__DisplayClass46", line 134, in <InvokeActionMethodFilterAsynchronouslyRecursive>b__3f
  File "System.Web.Mvc.Async.AsyncControllerActionInvoker+<>c__DisplayClass33", line unknown, in <BeginInvokeActionMethodWithFilters>b__32(System.IAsyncResult asyncResult)
  File "System.Web.Mvc.Async.AsyncResultWrapper+WrappedAsyncResult`1", line unknown, in CallEndDelegate(System.IAsyncResult asyncResult)
  File "System.Web.Mvc.Async.AsyncResultWrapper+WrappedAsyncResultBase`1", line 41, in End
  File "System.Web.Mvc.Async.AsyncControllerActionInvoker", line unknown, in EndInvokeActionMethodWithFilters(System.IAsyncResult asyncResult)
  File "System.Web.Mvc.Async.AsyncControllerActionInvoker+<>c__DisplayClass21+<>c__DisplayClass2b", line unknown, in <BeginInvokeAction>b__1c
  File "System.Web.Mvc.Async.AsyncControllerActionInvoker+<>c__DisplayClass21", line unknown, in <BeginInvokeAction>b__1e(System.IAsyncResult asyncResult)
EntityDoesNotExistException`1: Entity of type 'BusinessLogic.Models.GameDefinition' with Id '31179' does not exist.
```

**Comment by HolisticDeveloper** [comment]
These always seem to come from the same bot user agent:
```
Mozilla/5.0 (compatible; DotBot/1.2; +https://opensiteexplorer.org/dotbot; help@moz.com)
```

Not sure if it is trying to revisit links from a previous crawl or what. I couldn't find anything in the site that would be generating this type of link.
